before_install:
- sudo chmod 755 ./vendor/bin/youtube-dl
- sudo apt-get update -qq

after_success:
- bundle exec codeclimate-test-reporter

bundler_args: --without extras

rvm:
- 2.0.0 # Too old stable
- 2.1.9 # Old stable
- 2.2.5 # Previous Stable
- 2.3.1 # Current stable
- ruby-head # MRI head

cache: bundler

matrix:
  allow_failures:
  - rvm: ruby-head

notifications:
  slack: layer8x:cvixULdjCINfq7u9Zs1rS0VY
  email: false
